### ISSUE TITLE
上传文件失败，报 Stream Closed

### ISSUE THREAD

**Issue by thundeGG** [getActivity/EasyHttp#123]
## 问题描述
* 框架版本：11.0

* 问题描述：
上传一个11M的Mp4视频文件，进度百分百之后抛出Stream Close的异常 
* 复现步骤：
选择视频，调用接口上传
* 是否必现：填是/否
是
* 出现问题的手机信息：请填写出现问题的品牌和机型
HUAWEI MATE30 PRO
* 出现问题的安卓版本：请填写出现问题的 Android 版本
Android9.0
## 请回答

* 是部分机型还是所有机型都会出现：部分/全部（例如：某为，某 Android 版本会出现）
目前手上的安卓设备都有这个问题（小米）
* 框架最新的版本是否存在这个问题：是/否（如果用的是旧版本的话，建议升级看问题是否还存在）
是
* 是否已经查阅框架文档还未能解决的：是/否（文档会提供最常见的问题解答，可以看看是否有自己想要的）
是
* issue 是否有人曾提过类似的问题：是/否（看看曾经有人提过类似的问题，先参考一下别人是怎么解决的）
否
* 是否可以通过 Demo 来复现该问题：是/否（排查一下是不是自己的项目代码写得有问题导致的）
是
* 这个问题是不是后台自己的问题导致的：是/否（如果无法确定问题的原因，请先和后台开发人员协商联调，确认了问题是框架的再反馈给作者，如果是后台的问题作者也没用，最后还是要自己找后台处理才有用的）
应该不是，IOS上传正常
## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）
参数：
2022-06-13 10:52:45.186 11499-12297/com.hjq.easy.demo I/EasyHttp CircleApi: RequestCode = (MainActivity.java:222) 
2022-06-13 10:52:45.226 11499-12297/com.hjq.easy.demo I/EasyHttp CircleApi: RequestUrl = xxxxxxx(为了隐私隐藏了，如果需要可以联系我)
2022-06-13 10:52:45.226 11499-12297/com.hjq.easy.demo I/EasyHttp CircleApi: RequestMethod = POST
2022-06-13 10:52:45.227 11499-12297/com.hjq.easy.demo I/EasyHttp CircleApi: ----------------------------------------
2022-06-13 10:52:45.227 11499-12297/com.hjq.easy.demo I/EasyHttp CircleApi: token = MTY1NTAxOTIzNw==.eyJwcmltYXJ5IjoyMDIyMDQyNSwidXNlcl9pZCI6MTY1MDg2ODk2MTUxNzAwMCwiZXhwaXJlX3RpbWUiOjE2NTUzNjQ4Mzd9.NzQzNmNjZDI4MDExNzc0NWUxMmVmMTNkZjc4NzZlYTljY2FiZDQ0MA==
2022-06-13 10:52:45.227 11499-12297/com.hjq.easy.demo I/EasyHttp CircleApi: timestamp = 1655088765187
2022-06-13 10:52:45.227 11499-12297/com.hjq.easy.demo I/EasyHttp CircleApi: ----------------------------------------
2022-06-13 10:52:45.227 11499-12297/com.hjq.easy.demo I/EasyHttp CircleApi: area = "芜湖"
2022-06-13 10:52:45.227 11499-12297/com.hjq.easy.demo I/EasyHttp CircleApi: duration = "3539"
2022-06-13 10:52:45.227 11499-12297/com.hjq.easy.demo I/EasyHttp CircleApi: mtype = "3"
2022-06-13 10:52:45.227 11499-12297/com.hjq.easy.demo I/EasyHttp CircleApi: circle_id = "165501929246514"
2022-06-13 10:52:45.227 11499-12297/com.hjq.easy.demo I/EasyHttp CircleApi: file[0] = /storage/emulated/0/DCIM/Camera/VID_20220612_160410.mp4
报错：
    java.io.IOException: Stream Closed
        at java.io.FileInputStream.read(FileInputStream.java:306)
        at okio.InputStreamSource.read(Okio.kt:102)
        at okio.RealBufferedSink.writeAll(RealBufferedSink.kt:105)
        at com.hjq.http.body.UpdateBody.writeTo(UpdateBody.java:69)
        at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.java:173)
        at okhttp3.MultipartBody.writeTo(MultipartBody.java:114)
        at com.hjq.http.body.ProgressBody.writeTo(ProgressBody.java:62)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:201)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
2022-06-13 10:53:10.366 11499-12297/com.hjq.easy.demo E/EasyHttp CircleApi: 请求被中断，请重试
    com.hjq.http.exception.CancelException: 请求被中断，请重试
        at com.hjq.easy.demo.http.model.RequestHandler.requestFail(RequestHandler.java:168)
        at com.hjq.http.callback.NormalCallback.onFailure(NormalCallback.java:166)
        at com.hjq.http.callback.BaseCallback.onFailure(BaseCallback.java:93)
* 提供截图或视频（根据需要提供，此项不强制）
参数
![image](https://user-images.githubusercontent.com/13944095/173271313-8d7deb50-2343-4fc2-b9ea-e23909a89fe9.png)
报错
![image](https://user-images.githubusercontent.com/13944095/173271349-28d6c007-2ced-4f42-b11c-2c1938e00141.png)

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
小伙子，你把超时时间设置长一点看看有没有这个问题？

**Comment by thundeGG** [comment]
试过了，还是报着个错

**Comment by getActivity** [comment]
小伙子，请将修改后的 Demo 打成压缩包上传到这里，我这边做一下测试

**Comment by thundeGG** [comment]
不好意思，刚看到，整个压缩包太大了，就改了下mainActivity的
[MainActivity.zip](https://github.com/getActivity/EasyHttp/files/8936957/MainActivity.zip)

**Comment by getActivity** [comment]
<img width="874" alt="image" src="https://user-images.githubusercontent.com/28616817/175031755-7a597a79-db7c-48c3-a64f-4a9cf6f1ef00.png">

小伙子，CircleApi 这个类呢？

**Comment by getActivity** [comment]
还有你直接用 OkHttp 试一下看看会不会有这个问题？

**Comment by getActivity** [comment]
超过三天没有响应，自动关闭此 issue。
