### ISSUE TITLE
关于OKHttp报SocketTimout

### ISSUE THREAD

**Issue by AndyZeng1015** [getActivity/EasyHttp#139]
#### 问题描述

* 框架版本【必填】：11.2

* 问题描述【必填】：在使用本框架请求并返回body数据量比较大的时候，在通过body.string()获取数据时，有一定几率出现java.net.SocketTimeoutException: timeout
我在OKHttp的issues中也看到了很多提出socketTimeout的问题，但仍未解决。

* 复现步骤【必填】：1.选择文件上传；2.服务器识别结果通过接口返回；3.获取返回数据并加载（发生在这一步，通过postman测试接口可以正常使用）

* 是否必现【必填】：否

* 出现问题的手机信息【必填】：HONOR ViewPad 6

* 出现问题的安卓版本【必填】：Android 10

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否（但OKHttp中有提过类似的，但未能解决）

* 是否可以通过 Demo 来复现该问题【必答】：是

* 这个问题是不是后台自己的问题导致的【必答】：否

#### 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）
W/System.err: java.net.SocketTimeoutException: timeout
W/System.err:     at okio.Okio$4.newTimeoutException(Okio.java:232)
W/System.err:     at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
W/System.err:     at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
W/System.err:     at okio.RealBufferedSource.read(RealBufferedSource.java:47)
W/System.err:     at okhttp3.internal.http1.Http1Codec$AbstractSource.read(Http1Codec.java:363)
W/System.err:     at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:407)
W/System.err:     at okio.RealBufferedSource.read(RealBufferedSource.java:47)
W/System.err:     at okio.RealBufferedSource.exhausted(RealBufferedSource.java:57)
W/System.err:     at okio.InflaterSource.refill(InflaterSource.java:102)
W/System.err:     at okio.InflaterSource.read(InflaterSource.java:62)
W/System.err:     at okio.GzipSource.read(GzipSource.java:80)
W/System.err:     at okio.Buffer.writeAll(Buffer.java:1135)
W/System.err:     at okio.RealBufferedSource.readString(RealBufferedSource.java:199)
W/System.err:     at okhttp3.ResponseBody.string(ResponseBody.java:176)
W/System.err:     at com.scit.documentassistant.net.RequestHandler.requestSucceed(RequestHandler.java:108)
W/System.err:     at com.hjq.http.callback.NormalCallback.onResponse(NormalCallback.java:115)
W/System.err:     at com.hjq.http.callback.BaseCallback.onResponse(BaseCallback.java:57)
W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at java.lang.Thread.run(Thread.java:929)

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
<img width="821" alt="image" src="https://user-images.githubusercontent.com/28616817/192126200-6505bd01-1835-47b7-aea9-2fc5cdb11a63.png">

小伙子，请贴出相关的 issue 链接。

**Comment by getActivity** [comment]
另外我这边有两个问题，需要你这边解答一下：

1. 数据量比较大的时候会出现：你这个数据量大概念很模糊，我这边需要精确的数值，例如 10M 以上，或者 10M 左右。
2. 如果说 body.string() 会出现该问题，那么如果用 InputStream 或者 byte 数组的方式去读取是否也有同样的问题？

**Comment by BananaHuo** [comment]
> 最终让服务端将所有超时配置参数扩大一倍后

最终让服务端将所有超时配置参数扩大一倍后---这个您指的是nginx的所有超时配置吗？我在三星手机也遇到了这个情况，奇怪的是，我们的测试环境有一个接口可以，线上环境这个接口就是报timeout., 想请教下是哪里的问题呢？
