### ISSUE TITLE
Date类型提交是变为空对象疑问

### ISSUE THREAD

**Issue by Skqing** [getActivity/EasyHttp#158]
#### 问题描述

给一个对象设置一个时间值new Date()，如图所示：
![image](https://user-images.githubusercontent.com/1713001/220002047-a6ac190d-acd3-4bdc-96fe-3d9a92cad96e.png)

但在RequestInterceptor里观察到的值竟然变成了空对象，如图所示：
![QQ截图20230220110558](https://user-images.githubusercontent.com/1713001/220001981-c53bccc6-a792-4b88-9256-a38961f217d3.png)

从而导致提交服务端时服务端反序列化失败：

```java
org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: date only support string input; nested exception is com.alibaba.fastjson2.JSONException: date only support string input
	at com.alibaba.fastjson2.support.spring.http.converter.FastJsonHttpMessageConverter.readType(FastJsonHttpMessageConverter.java:110) ~[fastjson2-extension-spring5-2.0.25-20230219.173138-6.jar:?]
	at com.alibaba.fastjson2.support.spring.http.converter.FastJsonHttpMessageConverter.read(FastJsonHttpMessageConverter.java:77) ~[fastjson2-extension-spring5-2.0.25-20230219.173138-6.jar:?]
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver.readWithMessageConverters(AbstractMessageConverterMethodArgumentResolver.java:185) ~[spring-webmvc-5.3.15.jar:5.3.15]
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethodProcessor.java:160) ~[spring-webmvc-5.3.15.jar:5.3.15]
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:133) ~[spring-webmvc-5.3.15.jar:5.3.15]
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:122) ~[spring-web-5.3.15.jar:5.3.15]
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:179) ~[spring-web-5.3.15.jar:5.3.15]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:146) ~[spring-web-5.3.15.jar:5.3.15]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.15.jar:5.3.15]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.15.jar:5.3.15]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.15.jar:5.3.15]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.15.jar:5.3.15]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) [spring-webmvc-5.3.15.jar:5.3.15]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) [spring-webmvc-5.3.15.jar:5.3.15]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.3.15.jar:5.3.15]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) [spring-webmvc-5.3.15.jar:5.3.15]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) [tomcat-embed-core-9.0.56.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.3.15.jar:5.3.15]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) [tomcat-embed-core-9.0.56.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.56.jar:9.0.56]
```

这是服务端拿到的值：

```java
{xxxxxxxxxxxxxxx, locationTime":{}}
```

#### 请回答
有一个相关性的 https://github.com/getActivity/EasyHttp/issues/64
根据那个问题的回答，想问框架是否能够提供自己定义或者切换JSON序列化框架的功能呢？

* 框架文档是否有提及到此问题？【必答】：否

文档里相关性的就是对RequestBody进行定制，但如果这样定制每个请求方法都要改，能不能从更顶层去允许设置使用不同的JSON框架？例如可以在BodyRequest根据配置实例化不同的JSON框架实现的JsonBody。

我用fastjson2序列化后赋值到JsonBody中去得到了正确的结果，并且提交成功了：

.body(new JsonBody(JSON.toJSONString(note)))

![image](https://user-images.githubusercontent.com/1713001/220004673-662af280-b056-45be-9bb1-42517fcbca83.png)

虽然解决了问题，但不够优雅，每个请求都要先用fastjson2转成字符串然后赋值给JsonBody，如果可以在BodyRequest根据配置实例化不同的JSON框架实现的JsonBody就更好了。

**Comment by getActivity** [comment]
小伙子，我来解答一下你的两个疑问

1. 为什么不开放接口去序列化请求的 Api 类：这是因为框架对外提供了 HttpHeader、HttpIgnore、HttpRename 这三个注解，框架需要通过反射才能获取注解，如果交给外部去做，则不能实现这三个功能，当然不是说一定不行，如果要做也是可以的，拿 Gson 举例，需要先将 Bean 类解析成 Json，然后再从 Json 转成 Map 供框架使用，最后框架再去反射遍历一遍类里面的字段是否存在注解，但是这样极其浪费内存，需要转换 2 次，然后再反射 1 次，这样的代码效率极低下，我感觉没有必要。

2. 对于这个问题有没有什么好的解决方案：有，你不要把参数定义为 Date 类型，而是直接定义成 String 类型，然后在外层传入的时候做一下转换，类似下面这样：

```java
public final class XxxApi implements IRequestApi {

    @NonNull
    @Override
    public String getApi() {
        return "xxxx/";
    }

    private String date;

    public void setDate(Date date) {
        this.date = String.valueOf(date);
    }
}
```

**Comment by Skqing** [comment]
> 小伙子，我来解答一下你的两个疑问
> 
> 1. 为什么不开放接口去序列化请求的 Api 类：这是因为框架对外提供了 HttpHeader、HttpIgnore、HttpRename 这三个注解，框架需要通过反射才能获取注解，如果交给外部去做，则不能实现这三个功能，当然不是说一定不行，如果要做也是可以的，拿 Gson 举例，需要先将 Bean 类解析成 Json，然后再从 Json 转成 Map 供框架使用，最后框架再去反射遍历一遍类里面的字段是否存在注解，但是这样极其浪费内存，需要转换 2 次，然后再反射 1 次，这样的代码效率极低下，我感觉没有必要。
> 2. 对于这个问题有没有什么好的解决方案：有，你不要把参数定义为 Date 类型，而是直接定义成 String 类型，然后在外层传入的时候做一下转换，类似下面这样：
> 
> ```java
> public final class XxxApi implements IRequestApi {
> 
>     @NonNull
>     @Override
>     public String getApi() {
>         return "xxxx/";
>     }
> 
>     private String date;
> 
>     public void setDate(Date date) {
>         this.date = String.valueOf(date);
>     }
> }
> ```

1.第一点理解了
2.我自定义了个Fastjson2Body用.body(new Fastjson2Body(bean))这种方案解决了 ，没什么大问题。
