### ISSUE TITLE
如何在子线程上post数据

### ISSUE THREAD

**Issue by smalljames** [getActivity/EasyHttp#162]
#### 问题描述

* 框架版本【必填】：11.6

* 问题描述【必填】：创建一个子线程，调用EasyHttp.post，会出现“java.lang.IllegalStateException: Method addObserver must be called on the main thread”

* 复现步骤【必填】：这样添加一个子线程调用：

Runnable runnable = new Runnable() {
            @Override
            public void run() {
                       	//easyhttp请求 start *******************************
            EasyHttp.post(MainActivity.this)
                    .api(new SearchBlogsApi()
                            .setKeyword("搬砖不再有"))
                    .request(new HttpCallback<HttpData<SearchBlogsApi.Bean>>(MainEasyHttpActivity.this) {

                        @Override
                        public void onSucceed(HttpData<SearchBlogsApi.Bean> result) {
                            Toaster.show("Post 请求成功，请看日志");
                        }
                    });
                       //easyhttp请求 end  *******************************
            }
           };
   	Thread thread = new Thread(runnable);
        thread.start();

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：HarmonyOS 手机型号：HUWAI P40 Pro+，OPPO A96 5G等

* 出现问题的安卓版本【必填】：HarmonyOS版本3.0.0，Android版本12

* 问题信息的来源渠道【必填】：自己遇到的

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是

* 这个问题是不是后台自己的问题导致的【必答】：否

#### 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）
 E/DEBUG: java.lang.IllegalStateException: Method addObserver must be called on the main thread
E/DEBUG:     at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.java:317)
E/DEBUG:     at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:172)
E/DEBUG:     at com.hjq.http.lifecycle.HttpLifecycleManager.bind(HttpLifecycleManager.java:22)
E/DEBUG:     at com.hjq.http.callback.BaseCallback.<init>(BaseCallback.java:38)
E/DEBUG:     at com.hjq.http.callback.NormalCallback.<init>(NormalCallback.java:38)
E/DEBUG:     at com.hjq.http.request.HttpRequest.lambda$request$0$HttpRequest(HttpRequest.java:322)
E/DEBUG:     at com.hjq.http.request.-$$Lambda$HttpRequest$_S0R71tFgS0PSg696EUWjBemKxo.run(Unknown Source:6)
E/DEBUG:     at com.hjq.http.request.HttpRequest.request(HttpRequest.java:330)
E/DEBUG:     at com.hjq.http.request.BodyRequest.request(BodyRequest.java:107)

**Comment by smalljames** [comment]
重复提交了，关闭一个
