### ISSUE TITLE
网络请求修改请求头accept没有用

### ISSUE THREAD

**Issue by clbDream** [getActivity/EasyHttp#170]
#### 问题描述

* 请描述一下你的疑惑【必填】：后端PHP要求传递请求头accept为/json,我这边修改后没有效果，后端返回的网页无法解析

#### 请回答

* issue 是否有人曾提过类似的问题？【必答】无

* 框架文档是否有提及到此问题？【必答】：无

内容描述：
处理方式：
```
EasyConfig.with(okHttpClient)
                .addHeader("Accept", "/json")
                // 是否打印日志
                .setLogEnabled(AppConfig.isLogEnable())
                // 设置服务器配置
                .setServer(RequestServer())
                // 设置请求处理策略
                .setHandler(RequestHandler(application))
                // 设置请求重试次数
                .setRetryCount(1)
                .into()
```
返回的结果

```
服务器响应异常，请稍后再试，responseCode：422，message：Unprocessable Content
                                                                                                    com.hjq.http.exception.ResponseException: 服务器响应异常，请稍后再试，responseCode：422，message：Unprocessable Content
                                                                                                    	at com.tandaji.mobile.http.model.RequestHandler.requestSucceed(RequestHandler.kt:56)
                                                                                                    	at com.hjq.http.callback.NormalCallback.onResponse(NormalCallback.java:115)
                                                                                                    	at com.hjq.http.callback.BaseCallback.onResponse(BaseCallback.java:57)
                                                                                                    	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
                                                                                                    	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
```

**Comment by clbDream** [comment]
我使用接口调试工具试的是正常的

**Comment by getActivity** [comment]
<img width="917" alt="image" src="https://user-images.githubusercontent.com/28616817/233359248-efc6cecb-49ba-4edd-bc07-54d690418a28.png">

![Screenshot_2023_0420_195844](https://user-images.githubusercontent.com/28616817/233359329-092037c9-2ad2-448e-a317-c91e9ce638eb.jpg)

**Comment by getActivity** [comment]
超过两个星期没有响应，自动关闭此 issue。
