### ISSUE TITLE
[Bug]：java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType

### ISSUE THREAD

**Issue by xianningqis** [getActivity/EasyHttp#182]
### 框架版本【必填】

11.8

### 问题描述【必填】

Caused by java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType

### 复现步骤【必填】

冷启动调接口出现

### 是否必现【必填】

否

### 项目 targetSdkVersion【必填】

33

### 出现问题的手机信息【必填】

 Samsung Galaxy F52 5G

### 出现问题的安卓版本【必填】

11

### 问题信息的来源渠道【必填】

其他渠道

### 是部分机型还是所有机型都会出现【必答】

android 10\11\12\13

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

否

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

否

### 是否可以通过 Demo 来复现该问题【必答】

否

### 提供报错堆栈

```text
Caused by java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
       at com.hjq.http.EasyUtils.getGenericType(EasyUtils.java:421)
       at com.hjq.http.config.IRequestHandler.getGenericType(IRequestHandler.java)
       at com.hjq.http.callback.NormalCallback.setListener(NormalCallback.java:44)
       at com.hjq.http.request.HttpRequest.lambda$request$0(HttpRequest.java:323)
       at com.hjq.http.request.HttpRequest.request(HttpRequest.java:332)
       at com.xxx.guide.GuideActivity.dataInit(GuideActivity.kt:49)
       at com.xxx.base.WadeABase.onCreate(WadeABase.kt:39)
       at android.app.Activity.performCreate(Activity.java:8360)
       at android.app.Activity.performCreate(Activity.java:8338)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3894)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4078)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2423)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:334)
       at android.app.ActivityThread.main(ActivityThread.java:8333)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)
```

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题

请重新提一个 issue 并纠正以上问题
