### ISSUE TITLE
[Bug]：

### ISSUE THREAD

**Issue by zs18340282344** [getActivity/EasyHttp#196]
### 框架版本【必填】

implementation 'com.github.getActivity:EasyHttp:12.0'

### 问题描述【必填】

使用OnHttpListener这种形式请求开启混淆后闪退 混淆后日志，不混淆不报错 ，
日志：   java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
                                                                                                    	at com.hjq.http.EasyUtils.getGenericType(EasyUtils.java:421)
                                                                                                    	at com.hjq.http.config.IRequestHandler.getGenericType(IRequestHandler.java:106)
                                                                                                    	at com.hjq.http.callback.NormalCallback.setListener(NormalCallback.java:44)
                                                                                                    	at com.hjq.http.request.HttpRequest.lambda$request$0(HttpRequest.java:323)
                                                                                                    	at com.hjq.http.request.HttpRequest.$r8$lambda$_S0R71tFgS0PSg696EUWjBemKxo(HttpRequest.java:0)
                                                                                                    	at com.hjq.http.request.HttpRequest$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
                                                                                                    	at com.hjq.http.request.HttpRequest.request(HttpRequest.java:332)
                                                                                                    	at com.hjq.http.request.BodyRequest.request(BodyRequest.java:107)
                                                                                                    	at com.hy.goldloan.ui.login.LoginActivity.login(LoginActivity.kt:110)
                                                                                                    	at com.hy.goldloan.ui.login.LoginActivity.initView$lambda$0(LoginActivity.kt:29)
                                                                                                    	at com.hy.goldloan.ui.login.LoginActivity.$r8$lambda$-KDkde_uOQtLXtwUdfV5l1OOHZg(LoginActivity.kt:0)
                                                                                                    	at com.hy.goldloan.ui.login.LoginActivity$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass:0)
                                                                                                    	at android.view.View.performClick(View.java:6599)
                                                                                                    	at android.view.View.performClickInternal(View.java:6576)
                                                                                                    	at android.view.View.access$3100(View.java:780)
                                                                                                    	at android.view.View$PerformClick.run(View.java:25899)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:873)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:193)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6825)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)

### 复现步骤【必填】

     EasyHttp.post(ApplicationLifecycle.getInstance())
            .api(LoginApi().apply {
                setCopyright("202323")
                setDigitising("11")
            })
            .tag("abc")
            .request(object : OnHttpListener<HttpData<LoginApi.Bean.PreciseBean?>?> {
                override fun onHttpSuccess(result: HttpData<LoginApi.Bean.PreciseBean?>?) {}
                override fun onHttpFail(e: Exception) {}
            })

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

33

### 出现问题的手机信息【必填】

荣耀magic4

### 出现问题的安卓版本【必填】

13

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

所有

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

### 提供报错堆栈

```text
不混淆不报错
```

**Comment by getActivity** [comment]
小伙子，根据你提供的复现步骤，我用 Demo 复现不了你说的这个问题，劳烦你提供一个可供复现的 Demo 工程过来。

**Comment by getActivity** [comment]
[EasyHttp-12.2.aar.zip](https://github.com/getActivity/EasyHttp/files/12289509/EasyHttp-12.2.aar.zip)

**Comment by getActivity** [comment]
小伙子，我仔细看了一下代码，大概猜到是什么问题了，我尝试修复了一下，你用上面的 aar 替换后再试试看问题有没有出现？

**Comment by zs18340282344** [comment]
现在报新错误了  java.lang.ClassCastException: java.lang.Void cannot be cast to com.hy.goldloan.http.model.HttpData
                                                                                                    	at com.hy.goldloan.ui.login.LoginActivity$login$2.onHttpSuccess(LoginActivity.kt:114)
                                                                                                    	at com.hjq.http.listener.OnHttpListener.onHttpSuccess(OnHttpListener.java:24)
                                                                                                    	at com.hjq.http.callback.NormalCallback.dispatchHttpSuccessCallback(NormalCallback.java:168)
                                                                                                    	at com.hjq.http.callback.NormalCallback.lambda$onResponse$2(NormalCallback.java:126)
                                                                                                    	at com.hjq.http.callback.NormalCallback.$r8$lambda$wcbMidmTK8C891cCiS23RFOA1Is(NormalCallback.java:0)
                                                                                                    	at com.hjq.http.callback.NormalCallback$$ExternalSyntheticLambda2.run(R8$$SyntheticClass:0)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:873)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:193)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6825)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)

**Comment by zs18340282344** [comment]
测试域名：http://47.251.47.59:8403/cgi 
测试接口地址： /coflash/indicate
测试账号 123123
测试验证码 202323
测试请求字段 账号字段 digitising  验证码字段 copyright
您可以自己试一下

**Comment by zs18340282344** [comment]
用你新打的aar 生命周期监听那种格式也闪退了

**Comment by getActivity** [comment]
@zs18340282344 小伙子，我这边复现不了，劳烦你这边提供一个可供复现的 Demo 给我，我来排查一下是什么问题。

**Comment by getActivity** [comment]
@zs18340282344 小伙子，你这边要是没有办法提供 Demo，我就只能关闭 issue 了，等待下一个能复现的有缘人来做这件事了。

**Comment by getActivity** [comment]
超过两个星期没有响应，自动关闭此 issue。

**Comment by getActivity** [comment]
https://github.com/getActivity/EasyHttp/issues/221
