### ISSUE TITLE
[Bug]：java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to com.gj.aos.chat.mode.HttpData

### ISSUE THREAD

**Issue by leolsean** [getActivity/EasyHttp#198]
### 框架版本【必填】

12.0

### 问题描述【必填】

才开始开发,第一个接口就遇到这个问题:  直接解析到报文没问题,但是无法自动转为对应的实体对象!

java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to com.gj.aos.chat.mode.HttpData

### 复现步骤【必填】

随便调用一个接口, 会报错: 

如下是响应报文: 
{
                                                                                                        "retCode": "-1280",
                                                                                                        "retMsg": "-1280",
                                                                                                        "sign": "C/mvaI549JBHDUUuk3IO2AoxYL5qKVQH6OzNN5KSWqPf+tJ+NtLlRic0V/Kxs2dpFVgQhwUDxoi59x+m7sz+lixpLEeiKUGfRwjCgaqnhAxPLaiGss6pOzDtbxw+Y+++0ZDM9PdKXqseAi/tpWhvWVCbFfI54wBeEbJHVhqBTqX/5qDbjxL6PB3SmY1gHLF5a2W2hSFKEQ5CISTy3rxpHrH8rXTBwrUZJKZlC4hPX4oyKvuPnEwV1oN5Ak3YUOFcnVYd8OjFrrilBIk6kwriXhdVCLg4aDnMqA2SGYE66/2/M+YLNfYOWlC6OS/xORvMEnWG5QkCIpWZukrgWizOJw=="
                                                                                                    }

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

33

### 出现问题的手机信息【必填】

谷歌Pixel 3 XL

### 出现问题的安卓版本【必填】

12

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

都会有

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

是

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

未选择

### 提供报错堆栈

```text
FATAL EXCEPTION: main
                                                                                                    Process: me.hs.aos.tt, PID: 13313
                                                                                                    java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to com.gj.aos.chat.mode.HttpData
                                                                                                    	at com.gj.aos.chat.activity.LoginActivity$1.onHttpSuccess(LoginActivity.java:69)
                                                                                                    	at com.hjq.http.listener.HttpCallbackProxy.onHttpSuccess(HttpCallbackProxy.java:46)
                                                                                                    	at com.hjq.http.listener.HttpCallbackProxy.onHttpSuccess(HttpCallbackProxy.java:38)
                                                                                                    	at com.hjq.http.callback.NormalCallback.dispatchHttpSuccessCallback(NormalCallback.java:168)
                                                                                                    	at com.hjq.http.callback.NormalCallback.lambda$onResponse$2$com-hjq-http-callback-NormalCallback(NormalCallback.java:126)
                                                                                                    	at com.hjq.http.callback.NormalCallback$$ExternalSyntheticLambda4.run(Unknown Source:4)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7842)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by leolsean** [comment]
![image](https://github.com/getActivity/EasyHttp/assets/16144525/c50120f2-b625-43d4-887d-f494883ea2ba)
