### ISSUE TITLE
[Bug]：读取缓存失败

### ISSUE THREAD

**Issue by traywangjun** [getActivity/EasyHttp#232]
### 框架版本【必填】

12.8

### 问题描述【必填】

在readCache里调用GsonFactory.getSingletonGson().fromJson(cacheValue, type)解析异常
![image](https://github.com/getActivity/EasyHttp/assets/11623476/529d5cb6-b387-4466-91e7-55fc4653fa8a)

### 复现步骤【必填】

![image](https://github.com/getActivity/EasyHttp/assets/11623476/12fec45c-9a16-4dbe-8328-a9ec426922ee)
Api设置CacheMode，请求一次接口然后再次访问

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

34

### 出现问题的手机信息【必填】

三星s21

### 出现问题的安卓版本【必填】

14

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

全部

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

未选择

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

否

### 是否可以通过 Demo 来复现该问题【必答】

未选择

### 提供报错堆栈

```text
Abstract classes can't be instantiated! Register an InstanceCreator or a TypeAdapter for this type. Class name: [Ljava.lang.String;
                                                                                                    com.google.gson.JsonIOException: Abstract classes can't be instantiated! Register an InstanceCreator or a TypeAdapter for this type. Class name: [Ljava.lang.String;
                                                                                                    	at com.hjq.gson.factory.constructor.ExceptionConstructor.construct(ExceptionConstructor.java:22)
                                                                                                    	at com.hjq.gson.factory.constructor.KotlinDataClassDefaultValueConstructor.getTypeDefaultValue(KotlinDataClassDefaultValueConstructor.kt:91)
                                                                                                    	at com.hjq.gson.factory.constructor.KotlinDataClassDefaultValueConstructor.construct(KotlinDataClassDefaultValueConstructor.kt:59)
                                                                                                    	at com.hjq.gson.factory.constructor.ReflectSafeCreatorConstructor.construct(ReflectSafeCreatorConstructor.java:27)
                                                                                                    	at com.hjq.gson.factory.element.ReflectiveTypeAdapter.read(ReflectiveTypeAdapter.java:57)
                                                                                                    	at com.hjq.gson.factory.element.ReflectiveTypeUtils$1.read(ReflectiveTypeUtils.java:106)
                                                                                                    	at com.hjq.gson.factory.element.ReflectiveTypeAdapter.read(ReflectiveTypeAdapter.java:70)
                                                                                                    	at com.google.gson.Gson.fromJson(Gson.java:1227)
                                                                                                    	at com.google.gson.Gson.fromJson(Gson.java:1137)
                                                                                                    	at com.google.gson.Gson.fromJson(Gson.java:1047)
                                                                                                    	at com.google.gson.Gson.fromJson(Gson.java:1014)
                                                                                                    	at com.tt.dramatime.http.model.RequestHandler.readCache(RequestHandler.kt:186)
                                                                                                    	at com.hjq.http.callback.NormalCallback.start(NormalCallback.java:54)
                                                                                                    	at com.hjq.http.request.HttpRequest.lambda$null$1$com-hjq-http-request-HttpRequest(HttpRequest.java:321)
                                                                                                    	at com.hjq.http.request.HttpRequest$$ExternalSyntheticLambda3.run(Unknown Source:6)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
```

### 提供截图或视频

![image](https://github.com/getActivity/EasyHttp/assets/11623476/0559ecea-9a4b-47d4-9abb-7a42acb07883)

**Comment by getActivity** [comment]
<img width="393" alt="image" src="https://github.com/getActivity/EasyHttp/assets/28616817/23dd114c-7598-455f-aecc-5299b270d70f">

<img width="348" alt="image" src="https://github.com/getActivity/EasyHttp/assets/28616817/536a3108-d171-4881-9c41-0860293db2f8">

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题

请重新提一个 issue 并纠正以上问题
