### ISSUE TITLE
[Bug]：上传文件，进度条到100%后立即报IOException: Stream Closed

### ISSUE THREAD

**Issue by zdw2014** [getActivity/EasyHttp#259]
### 框架版本【必填】

12.8

### 问题描述【必填】

按照文档进行编写上传文件，在进度达到100%后十多ms内就会报异常IOException: Stream Closed

### 复现步骤【必填】

请求地址：http://123.126.5.178:10032/bank_inter/lockbox/file/uploadFile
直接上传就会复现。通过postman类的工具不会有此现象。

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

30

### 出现问题的手机信息【必填】

定制机型

### 出现问题的安卓版本【必填】

7.1

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

部分

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

### 提供报错堆栈

```text
Stream Closed
java.io.IOException: Stream Closed
	at java.io.FileInputStream.read(FileInputStream.java:246)
	at okio.Okio$2.read(Okio.java:140)
	at okio.RealBufferedSink.writeAll(RealBufferedSink.java:105)
	at com.hjq.http.body.UpdateStreamRequestBody.writeTo(UpdateStreamRequestBody.java:67)
	at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.java:173)
	at okhttp3.MultipartBody.writeTo(MultipartBody.java:114)
	at com.hjq.http.body.WrapperRequestBody.writeTo(WrapperRequestBody.java:35)
	at com.hjq.http.body.ProgressMonitorRequestBody.writeTo(ProgressMonitorRequestBody.java:48)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at com.android.tools.profiler.agent.okhttp.OkHttp3Interceptor.intercept(OkHttp3Interceptor.java:57)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:201)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
com.hjq.http.exception.CancelException: 
	at com.syb.cjwl.locker.http.RequestHandler.parseException(RequestHandler.java:184)
	at com.syb.cjwl.locker.http.RequestHandler.requestFail(RequestHandler.java:146)
	at com.hjq.http.callback.NormalCallback.onHttpFailure(NormalCallback.java:145)
	at com.hjq.http.callback.BaseCallback.onFailure(BaseCallback.java:108)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:211)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
```

### 提供截图或视频

无

### 提供解决方案

无

**Comment by getActivity** [comment]
你试试直接用 OkHttp 请求看看是否也有同样的问题？

**Comment by zdw2014** [comment]
谢谢大佬回复。
删除了.idea/.gradle/build等编译文件，重新导入了项目，它恢复正常了

**Comment by shangxiazuoyou** [comment]
我也遇到了这个问题，删除了.idea/.gradle/build等编译文件，重新导入了项目，没有恢复正常

**Comment by xhg221** [comment]
我也遇到这个问题了，使用的时EasyHttp  13.0，进度100%时，Stream Closed。
同样的file文件，我使用自定义的OKhttp，能正常上传。
请问能给修复下吗？[](url)

**Comment by getActivity** [comment]
> 我也遇到这个问题了，使用的时EasyHttp  13.0，进度100%时，Stream Closed。
> 同样的file文件，我使用自定义的OKhttp，能正常上传。
> 请问能给修复下吗？[](url)

能提供一个可供复现的 Demo 上传到这里吗？
