### ISSUE TITLE
父类和子类存在相同属性时解析报错

### ISSUE THREAD

**Issue by Skqing** [getActivity/EasyHttp#42]
implementation 'com.hjq:http:9.2'

错误：
```
class com.xxx.bean.XxxBean declares multiple JSON fields named createTime
    com.hjq.http.exception.HttpException: class com.xxx.bean.XxxBean declares multiple JSON fields named createTime
        at com.cloudwave.lvzaimo.http.model.RequestHandler.requestFail(RequestHandler.java:197)
        at com.hjq.http.callback.NormalCallback.onFailure(NormalCallback.java:61)
        at com.hjq.http.callback.BaseCallback.onResponse(BaseCallback.java:56)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

为什么父类和子类存在相同属性呢，原本打算是通用属性放到父类，但因为用了greendao的库，greendao在保存对象的时候不会去读取父类的属性生成列因此只能在某个子类里加上跟父类相同的属性。但这有导致用'com.hjq:http:9.2'时报错。

**Comment by Skqing** [comment]
另外，请问一下解析能不能换成fastjson呢，或者说做成可选，GSON或者FASTJSON根据配置来

**Comment by Skqing** [comment]
对子类属性加上 @Expose(deserialize = false) 注解也并没有什么效果依然报错

**Comment by getActivity** [comment]
EasyHttp 是不带任何 Json 解析功能的，你可以在 RequestHandler 类中手动替换掉 Gson 框架

**Comment by Skqing** [comment]
另外请教一下greendao无法继承的问题您是什么方案？

**Comment by getActivity** [comment]
我没用过这个框架，不能给到你答案

**Comment by Skqing** [comment]
JSON那个问题我换成fastjson了，但因为泛型的问题不能在上层进行反序列化，只能在每个调用的地方的回调方法里反序列化，没办法了暂时只能这样。

还有请问一下您用的什么持久框架呢？保存数据到本地这方面

**Comment by getActivity** [comment]
推荐一个我之前用过的框架给你：https://github.com/leavesC/DoKV

**Comment by Skqing** [comment]
多谢，加油！
