### ISSUE TITLE
ContentResolver insert 返回的uri为null

### ISSUE THREAD

**Issue by mccccccmike** [getActivity/EasyHttp#86]
下面加粗的为app crash的代码位置
```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                ToastUtils.show("Android 10");
                // 适配 Android 10 分区存储特性
                ContentValues values = new ContentValues();
                // 设置显示的文件名
                values.put(MediaStore.Downloads.DISPLAY_NAME, fileName);
                // 生成一个新的 uri 路径
                outputUri = getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, values);
                **file = new FileContentResolver(getContentResolver(), outputUri, fileName);**
            } else {
                file = new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS), fileName);
            }
```

下面为报错信息
```
Process: com.littlelives.familyroom.debug, PID: 28561
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
        at com.hjq.http.model.FileContentResolver.<init>(FileContentResolver.java:51)
        at com.littlelives.familyroom.ui.common.ImageViewActivity.download(ImageViewActivity.kt:336)
```
        

更新，运行官方demo也崩溃
华为P40
Homony 2.0

请大佬给一下建议:)

**Comment by getActivity** [comment]
小伙子，你这个问题属于分区存储的问题，不属于框架的问题，我目前只处理和框架相关的问题，如果是个人的使用问题需要你自行排查及解决。

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。

**Comment by mccccccmike** [comment]
好的，谢谢，没有了
